BINARY  := box
PREFIX  ?= $(HOME)/.local
SWIFT   ?= swift
CONFIG  ?= release
ENTL    := box.entitlements
BUILT    = .build/$(CONFIG)/$(BINARY)
STAMP   := Sources/BoxKit/VersionStamp.swift
VERSION := $(shell git describe --tags --always --dirty 2>/dev/null)
COMPDIR ?= completions

.PHONY: all build install gen-assets clean run fmt version-stamp completions

all: build

# Regenerate the embedded asset blobs from assets/files/*.
gen-assets:
	./scripts/gen-embedded-assets.sh

# Stamp the build's version from `git describe` into the generated constant.
# `box --version` / `box version` read it via BoxKit.Version.box.
version-stamp:
	@printf '// Code generated by `make version-stamp`. DO NOT EDIT.\nlet boxVersionStamp: String? = "%s"\n' '$(VERSION)' > $(STAMP)
	@echo "stamped box version: $(VERSION)"

# Generate shell completion scripts (bash, zsh, fish) into $(COMPDIR).
completions: build
	@mkdir -p $(COMPDIR)
	$(BUILT) --generate-completion-script bash > $(COMPDIR)/box.bash
	$(BUILT) --generate-completion-script zsh  > $(COMPDIR)/_box
	$(BUILT) --generate-completion-script fish > $(COMPDIR)/box.fish
	@echo "wrote $(COMPDIR)/{box.bash,_box,box.fish}"

build: version-stamp
	$(SWIFT) build -c $(CONFIG)
	codesign --force --sign - --entitlements $(ENTL) $(BUILT)

install: build
	mkdir -p $(PREFIX)/bin
	install -m 0755 $(BUILT) $(PREFIX)/bin/$(BINARY)
	# re-sign the installed copy with the virtualization entitlement
	codesign --force --sign - --entitlements $(ENTL) $(PREFIX)/bin/$(BINARY)
	@echo "installed $(PREFIX)/bin/$(BINARY)"

fmt:
	$(SWIFT) format --in-place --recursive Sources/

clean:
	$(SWIFT) package clean
	rm -rf .build
