#!/usr/bin/env bash
# Generate Sources/BoxKit/EmbeddedAssets.swift from assets/files/*.
# Each asset is base64-encoded (robust against quoting) and decoded at runtime
# in materialize(). Re-run via `make gen-assets` whenever assets/files changes.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="Sources/BoxKit/EmbeddedAssets.swift"

{
    echo "// Code generated by scripts/gen-embedded-assets.sh. DO NOT EDIT."
    echo "// Regenerate with: make gen-assets"
    echo
    echo "import Foundation"
    echo
    echo "enum EmbeddedAssets {"
    echo "    /// base64-encoded asset contents, keyed by their path within the box dir."
    echo "    static let base64: [String: String] = ["
    # name = path within the box directory; src = file under assets/files
    emit() { # <src-file> <box-rel-path>
        local b64
        b64="$(base64 < "assets/files/$1" | tr -d '\n')"
        echo "        \"$2\": \"$b64\","
    }
    # Same, but reading from an arbitrary repo-relative source path.
    emit_from() { # <repo-rel-src> <box-rel-path>
        local b64
        b64="$(base64 < "$1" | tr -d '\n')"
        echo "        \"$2\": \"$b64\","
    }
    emit Dockerfile     "Dockerfile"
    emit entrypoint.sh  "entrypoint.sh"
    emit xclip-shim.sh  "xclip-shim.sh"
    emit box-layers.dockerfile "box-layers.dockerfile"
    emit allowlist.txt  "config/allowlist.txt"
    # box-proxy crate source: the image build stage compiles it into the sidecar.
    emit_from proxy/Cargo.toml "proxy/Cargo.toml"
    emit_from proxy/Cargo.lock "proxy/Cargo.lock"
    for f in proxy/src/*.rs; do
        emit_from "$f" "proxy/src/$(basename "$f")"
    done
    echo "    ]"
    echo "}"
} > "$OUT"

echo "wrote $OUT"
